# Generated by Django 4.1.2 on 2022-11-03 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vazhipadu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vazhipadu_name', models.CharField(max_length=100, unique=True)),
                ('price', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('person_name', models.CharField(max_length=50)),
                ('nakshathram', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('just_date', models.DateField(auto_now_add=True)),
                ('vazhipadu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.vazhipadu')),
            ],
        ),
    ]
